### ISSUE TITLE
032A 홈페이지 배경 도와주세요

### ISSUE THREAD

**Issue by gold9598** [17-1-SKKU-OSS/178A#9]
HTML로 그림 하나가 화면을 꽉채우게 도와주실수 있나요

**Comment by nuxlear** [comment]
no-repeat 옵션을 style 태그 안에 넣어주시면 될거 같네요

**Comment by nuxlear** [comment]
css 코드 추가해서 repo에 commit 해드렸습니다

**Comment by whitecloudy** [comment]
더이상 질문 없으시다면 이슈 닫겠습니다.
